services:
  - type: web
    name: dsaengine-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: MASTER_API_2026
        sync: false
